name: build and package

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

env:
  SKIA_VERSION: "m102-861e4743af"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        build_type: [MinSizeRel]
        enable_ui: [on]
            
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'aseprite/aseprite'
        submodules: 'recursive'
        
    - name: Cache Skia
      id: cache-skia
      uses: actions/cache@v3
      with:
        path: skia
        key: ${{ runner.os }}-skia-${{ env.SKIA_VERSION }}
    
    - name: Download and Unzip Skia
      if: steps.cache-skia.outputs.cache-hit != 'true'
      shell: bash
      run: |
        FILE_NAME=""
        if [[ "${{ runner.os }}" == "Linux" ]]; then
          FILE_NAME="Skia-Linux-Release-x64-libstdc++.zip"
        elif [[ "${{ runner.os }}" == "macOS" ]]; then
          FILE_NAME="Skia-macOS-Release-x64.zip"
        elif [[ "${{ runner.os }}" == "Windows" ]]; then
          FILE_NAME="Skia-Windows-Release-x64.zip"
        fi
        echo "FILE_NAME=$FILE_NAME"
        SKIA_URL=https://github.com/aseprite/skia/releases/download/${{ env.SKIA_VERSION }}/$FILE_NAME
        echo "SKIA_URL=$SKIA_URL"
        curl -L -o $FILE_NAME $SKIA_URL
        mkdir -p skia
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          powershell -command "Expand-Archive -Path $FILE_NAME -DestinationPath ./skia"
        else
          unzip -q $FILE_NAME -d ./skia
        fi
        
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1
      if: runner.os == 'Linux'
      with:
        key: ${{ matrix.os }}-${{ matrix.enable_ui }}
        
    - uses: turtlesec-no/get-ninja@main
    
    - uses: ilammy/msvc-dev-cmd@v1
      if: runner.os == 'Windows'
      
    - name: Workaround for windows-2022 and cmake 3.25.0
      if: runner.os == 'Windows'
      shell: bash
      run: rm -rf C:/Strawberry/
      
    - name: Install Dependencies
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Linux" ]] ; then
          sudo apt-get update -qq
          sudo apt-get install -y \
            g++ clang libc++-dev libc++abi-dev cmake ninja-build libx11-dev libxcursor-dev libxi-dev libgl1-mesa-dev libfontconfig1-dev
        fi
        
    - name: Generating Makefiles
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Windows" ]] ; then
          export enable_ccache=off
          export skia_lib=./skia/out/Release-x64/skia.lib
        else
          export enable_ccache=on
          export skia_lib=./skia/out/Release-x64/libskia.a
        fi
        cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 \
          -DENABLE_TESTS=ON \
          -DENABLE_UI=${{ matrix.enable_ui }} \
          -DLAF_BACKEND=skia \
          -DSKIA_DIR=./skia \
          -DSKIA_LIBRARY_DIR=./skia/out/Release-x64 \
          -DSKIA_LIBRARY=$skia_lib \
          -DENABLE_CCACHE=$enable_ccache
          
    - name: Compiling
      shell: bash
      run: |
        cd build && ninja

    - name: install cpanm and multiple modules
      uses: shogo82148/actions-setup-perl@v1
      with:
        install-modules: |
          Text::Template

    - name: Build OpenSSL
      shell: bash
      run: |
        git clone https://github.com/openssl/openssl.git
        cd openssl
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          perl Configure VC-WIN64A
        fi
        git checkout OpenSSL_1_1_1w
        ./config
        make

    - name: Debug
      shell: bash
      run: ls -laR

    - name: Prepare
      shell: bash
      run: |
        cd build/bin
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          powershell -command "Get-ChildItem -Filter '*_tests*' | Remove-Item -Force"
          powershell -command "Get-ChildItem '../../openssl/' -Include *libcrypto*1*.dll -Recurse | Copy-Item -Destination ."
        else
          rm -f *_tests*
          find ../../openssl/ -type f -name '*libcrypto*1*' -exec cp {} . \;
        fi
        echo '# This file is here so Aseprite works as a portable program' > aseprite.ini
          
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-${{ matrix.os }}-${{ matrix.build_type }}-ui_${{ matrix.enable_ui }}
        path: build/bin/
        retention-days: 2
